### PR TITLE
Use es-config-airbnb 16.0.0 and update dependencies

### PR DESCRIPTION
**Pull request by drudolf**
Only thing that bugs me right now is the "function-paren-newline" rule.

### CODE REVIEW

**Comment by godban** [comment]
@drudolf what's a bug?

**Comment by drudolf** [comment]
It "annoys" me because it forces you to use the first parameter on the same line. I would go with "consistent" instead.

**Comment by godban** [comment]
@drudolf could you give an example, please?

**Comment by drudolf** [comment]
@godban They enabled `'function-paren-newline': ['error', 'multiline']` so this is not valid anymore:

```
throw new Error(
    `${adapterClass.name} has invalid function "${method}" - use "_" prefix for private methods`,
);
```

**Comment by godban** [comment]
we can release `v2.1.0` afterwards

**Comment by drudolf** [comment]
@godban BTW I just made these changes today because I somehow had `eslint-plugin-jsx-a11y` in `6.0.1` in tv react client and npm was complaining that zattoo/eslint-config `2.0.3` required `5.1.1`. Then I saw that there was a new `eslint-config-airbnb` version and then... I couldnt stop... :grin:

**Pull request merged**
